RedCdn.ClassRoom.BMS/Controllers/SystemManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using GM.Utilities;
using RedCdn.ClassRoom.BMS.Models;
using RedCdn.ClassRoom.BMS.Services;
using Redcdn.ClassRoom.Facade;

namespace RedCdn.ClassRoom.BMS.Controllers
{
   //[Authorize(Users = "admin")]
    public class SystemManagerController : ControllerBase
    {
        //
        // GET: /SystemManager/

        [Authorize(Users = "admin")]
        public ActionResult Edit()
        {
            ViewBag.TitleDesc = "系统管理";
            try {
                var dto = FacadeFactory.Instance.Get<ISystemManager>().GetSchoolManager();
                if (dto == null)
                    return View();

                Mapper.CreateMap<SystemManagerDto, SystemManagerModule>().ConvertUsing<NumberPoolsConverter>();
                var viewModel = Mapper.Map<SystemManagerDto, SystemManagerModule>(dto);
                return View(viewModel);
            } catch (Exception) {
                throw;
            }
        }

        [Authorize(Users = "admin")]
        [HttpPost]
        public ActionResult EditInfo(SystemManagerModule model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var listNum = new List<string>();
                    if (model.NumberPools != null)
                    {
                        if (model.NumberPools.Contains("\n"))
                            listNum = model.NumberPools.Split('\n').ToList();
                        else
                            listNum.Add(model.NumberPools);
                    }

                    var sysManager = new SystemManagerDto()
                    {
                       
                        SchoolManagerAccount = model.SchoolManagerAccount,
                        SchoolManagerPassWord = model.SchoolManagerPassWord,
                        SchoolManagerName = model.SchoolManagerName,
                        NumberPool = listNum.ToArray()
                    };

                    if (model.Id==null)
                        FacadeFactory.Instance.Get<ISystemManager>().Create(sysManager);
                    else
                    {
                        sysManager.Id = model.Id.Value;
                        FacadeFactory.Instance.Get<ISystemManager>().Update(sysManager);
                    }

                    return Json(new { success = true, message = "修改成功。" });
                }

                return Json(new { success = false, message = "提交的数据不正确。" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult MyInfo()
        {
            var dto = FacadeFactory.Instance.Get<ISystemManager>().GetById(Passport.UserId);
            if (dto != null) {
                var model = new PersonalModel() {
                    Id = dto.Id,
                    ManagerAccount = dto.SchoolManagerAccount,
                    ManagerName = dto.SchoolManagerName,
                };
                return View(model);
            }
            return View();
        }

        [HttpPost]
        public ActionResult ModifyInfo(PersonalModel model)
        {
            if (ModelState.IsValid) {

                try
                {
                    FacadeFactory.Instance.Get<ISystemManager>().ModifyPersonalInfo(Passport.UserId, model.ManagerName, model.NewPassWord, model.ConfirmPassWord);

                    return Json(new { success = true, message = "修改个人信息成功。" });
                }
                catch (Exception ex)
                {
                    Logger.WriteError(LogCatalogs.OperationHits, "修改个人信息失败",ex);
                    return Json(new { success = false, message = "修改个人信息失败。" });
                }
            }
            return Json(new { success = false, message = "修改个人信息失败。" });
        }

        public ActionResult Logout() {
            AuthenticationService.Instance.SignOut();

            return RedirectToAction("logon");
        }
    }
}

RedCdn.ClassRoom.BMS/Views/SystemManager/Edit.cshtml
@model RedCdn.ClassRoom.BMS.SystemManagerModule

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Scripts/layer/layer.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type=" text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
@using (Html.BeginForm("EditInfo", "SystemManager", FormMethod.Post, new Dictionary<string, object>() { { "id", "formsystemmanage" } })) {
    <div class="clear">
        <h6 class="tips"><span></span></h6>
        <ul class="management" ngdesc="@ViewBag.TitleDesc">
            <li>
                <span><font>校园管理员账号：</font></span>
                @Html.HiddenFor(model => model.Id)
                @Html.TextBoxFor(model => model.SchoolManagerAccount)
                <font class="wenzig">@Html.ValidationMessageFor(model => model.SchoolManagerAccount)</font>
            </li>
            <li><span><font> 校园管理员名称：</font></span>@Html.TextBoxFor(model => model.SchoolManagerName)<font class="wenzig">@Html.ValidationMessageFor(model => model.SchoolManagerName)</font></li>
            <li><span><font> 校园管理员密码：</font></span>@Html.PasswordFor(model => model.SchoolManagerPassWord)</li>
            <li>
                <span><font class="wenzitop"> 同步教室号码池：</font></span>
                @Html.TextAreaFor(model => model.NumberPools, new Dictionary<string, object>()
                {
                    {"max-height", "100px"},
                    {"max-width", "200px"},
                    {"resize", "none"},
                    {"outline", "none"},
                    {"width", "200px"},
                    {"height", "100px"}
                })
                <font class="wenzig">
                    供给校园同步教室的号码池，每行一个号码，多个号码已回车换行分割 例子
                    如下：69001001  69001002
                </font>
            </li>
            <li style="height: 120px; margin-top: 60px;">
                @*<a class="xiaobtn" href="#" onclick="submitForm('#formsystemmanage')" style="margin-left: 131px; margin-top: 0px;">保存</a>*@ 
                <input style="margin-top: 0; margin-left: 131px;" type="button" class="submit" onmouseover=" this.style.backgroundPosition = 'left -33px' " onmouseout=" this.style.backgroundPosition = 'left top' " onclick=" submitForm('#formsystemmanage') " value="保 存" />
                <a href="@Url.Action("index", "classroom", null)" style="margin-top: 0px; margin-left: 60px;" class="xiaobtn">返 回</a>
                <br />
            </li>
        </ul>
    </div>
}


<script type="text/javascript">
    $(function () {
        createnavigation();
    });

    function submitForm(formid) {

        var account = $('#SchoolManagerAccount').val();
        var anmae = $('#SchoolManagerName').val();
        if (account === "" || anmae === "")
            return;


        $(formid).ajaxSubmit({
            //beforeSend: function () {
            //  //  $.messager.progress({
            //      //  text: '正在等待提交结果，请稍候...'
            //    });
            //},
            success: function (result, statusText) {
                layer.msg(result.message, { icon: 1, time: 1000 });
                
            },
            error: function () {
                //alert('系统错误，请稍候再试');
                layer.alert('系统错误，请稍候再试', { icon: 7, time: 3000 });
            },
            complete: function () {
                // $.messager.progress('close');
                location.href = '@Url.Action("edit","systemmanager")';
            }
        });
    }

    /*创建面包屑导航菜单*/
    function createnavigation() {
        var ngDesc = $('ul.management').attr('ngdesc');

        var div = $('div.position');
        div.html('');
        div.append('当前位置： <a href="/">首页 </a> >'+ngDesc);
    }
</script>

RedCdn.ClassRoom.BMS/Views/SystemManager/MyInfo.cshtml
@model RedCdn.ClassRoom.BMS.PersonalModel
@{
    ViewBag.Title = "个人信息修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type=" text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/layer/layer.js")" type="text/javascript"></script>
<div class="clear">
    <h6 class="tips"><span>修改个人信息</span></h6>
    <ul class="management">
       <form id="myinfoform" method="post" action="">
            @Html.HiddenFor(model=>model.Id)
            <li><span><font>管理员账号：</font></span>@Html.TextBoxFor(model => model.ManagerAccount,new {@readonly="readonly"})</li>
            <li><span><font> 管理员名称：</font></span>@Html.TextBoxFor(model => model.ManagerName, new { @id = "managername", @name = "managername" })@Html.ValidationMessageFor(model=>model.ManagerName)</li>
            <li><span><font> 新    密   码：</font></span>@Html.PasswordFor(model=>model.NewPassWord)@Html.ValidationMessageFor(model=>model.NewPassWord)</li>
            <li><span><font> 重复新密码：</font></span>@Html.PasswordFor(model=>model.ConfirmPassWord)@Html.ValidationMessageFor(model=>model.ConfirmPassWord)</li>
            <li style="height: 120px; margin-top: 60px;">
                <input style="margin-top: 0; margin-left: 222px;" type="button" class="submit" onmouseover=" this.style.backgroundPosition = 'left -33px' " onmouseout=" this.style.backgroundPosition = 'left top' " onclick="save()" value="保 存">
                <a href="/"><input style="margin-top: 0; margin-left: 60px;" type="button" class="submit" onmouseover=" this.style.backgroundPosition = 'left -33px' " onmouseout=" this.style.backgroundPosition = 'left top' " value="返 回"></a>
            </li>
        </form>
    </ul>
</div>

<script type="text/javascript">
    $(function () {
        createnavigation();
    });

    function createnavigation() {
        var div = $('div.position');
        div.html('');
        div.append('当前位置： <a href="/">首页 </a> >个人信息');
    }
    
    function save() {
        $.ajax({            
            url: '@Url.Action("ModifyInfo", "SystemManager")',
            type: 'post',
            data: $('#myinfoform').serialize(),
            cache: false,
            dataType: 'json',
            success:function(result) {
                layer.alert(result.message, { icon: 1, time: 1000 });
            },
            error:function(XMLHttpRequest, textStatus, errorThrown) {
                layer.alert(textStatus, { icon: 1, time: 1000 });
            }
        });
    }

</script>