RedCdn.ClassRoom.BMS/Controllers/CurriculumNumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GM.Utilities;
using RedCdn.ClassRoom.BMS.Models;
using Redcdn.ClassRoom.Facade;

namespace RedCdn.ClassRoom.BMS.Controllers
{
    [Authorize]
    public class CurriculumNumberController : ControllerBase
    {
        int pageSize = SettingConfig.Instance.PageSize;
        public ActionResult Index(int page = 0, int count = 0)
        {
            var pagep = CreateQueryPageParameter(page, pageSize);
            return GetIndexView("index", pagep);
        }

        ActionResult GetIndexView(string viewname, ContentQueryPageParameter pagep) {
            var index = new IndexPaging<CurriculumNumberModel>();
            index.CurriculumEidtInfo = CurriculumEidtInfo.Load();
            var queryList = FacadeFactory.Instance.Get<ICurriculumNumberManager>().GetList(pagep);
            QueryExtracted(index.Paging, queryList);
            index.Paging.TotalCount = queryList.TotalCount;

            return View(viewname, index);
        }

        public ActionResult Query(int page = 0, int count = 0) {
            var pagep = CreateQueryPageParameter(page, count);

            var paging = new PagingQueryResultDto<CurriculumNumberModel>();
            var queryList = FacadeFactory.Instance.Get<ICurriculumNumberManager>().GetList(pagep);
            QueryExtracted(paging, queryList);
            paging.TotalCount = queryList.TotalCount;

            return PartialView("_CurriculumNumberList", paging);
        }

        [HttpPost]
        public ActionResult Create(CurriculumNumberModel model) {

            try
            {
                DateTime classStarttime = Convert.ToDateTime(string.Format("{0} {1}", "2001-1-1", model.StarTime.GetDateTimeFormats('t')[0]));
                model.StarTime = classStarttime;

                if (model.Duration == 0)
                    model.Duration = 45;
                var viewModel = ConvertToDto(model);
                FacadeFactory.Instance.Get<ICurriculumNumberManager>().Create(viewModel);

                return Json(new { success = true, message = "添加成功" });
            }
            catch (Exception ex)
            {
                Logger.WriteError(LogCatalogs.OperationHits, "添加课序失败", ex);
                return Json(new { success = false, message = "添加失败" });
            }
        }

        [HttpPost]
        public ActionResult Edit(CurriculumNumberModel model, int page = 0) {
            try
            {
                ViewBag.Page = page;
                DateTime classStarttime = Convert.ToDateTime(string.Format("{0} {1}", "2001-1-1", model.StarTime.GetDateTimeFormats('t')[0]));
                model.StarTime = classStarttime;

                if (model.Duration == 0)
                    model.Duration = 45;
                FacadeFactory.Instance.Get<ICurriculumNumberManager>().Update(ConvertToDto(model));

                return Json(new { success = true, message = "编辑成功" });
            }
            catch (Exception ex)
            {
                Logger.WriteError(LogCatalogs.OperationHits, "更新课序失败", ex);
                return Json(new { success = false, message = "编辑失败" });
            }
        }

        public ActionResult Edit(int id=0,int page=0)
        {
            ViewBag.Page = page;
            if (id == 0)
            {
                ViewBag.TitleDesc = "创建课序";
                ViewBag.IsCreate = true;
            }
            else
            {
                ViewBag.TitleDesc = "编辑课序";
                ViewBag.IsCreate = false;
            }

            var dto = FacadeFactory.Instance.Get<ICurriculumNumberManager>().Get(id);
            if (dto == null)
                return View(new CurriculumNumberModel());

            var viewModel = ConvertToModel(dto);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id) {
            try {
                FacadeFactory.Instance.Get<ICurriculumNumberManager>().Delete(id);
                return Json(new { success = true, message = "删除课序成功" });
            } catch (Exception ex) {
                return Json(new { success = false, message = "课序已绑定课表,不允许删除" });
            }
        }

        int GetInt(int num) {
            return num < 0 ? 0 : num;
        }

        private void QueryExtracted(PagingQueryResultDto<CurriculumNumberModel> paging, PagingQueryResultDto<CurriculumNumberDto> queryList) {
            queryList.Result.ForEach(r => {
                var viewModel = ConvertToModel(r);
                paging.Result.Add(viewModel);
            });
        }

        ContentQueryPageParameter CreateQueryPageParameter(int page, int count) {
            ViewBag.PSize = pageSize;
            return new ContentQueryPageParameter() { StartIndex = page, PageSize = count, OrderFields = new List<string> { "id" }, OrderFlag = true };
        }

        CurriculumNumberDto ConvertToDto(CurriculumNumberModel model) {
            var result = new CurriculumNumberDto();
            AutoMapperWrapper.Instance.Map<CurriculumNumberModel, CurriculumNumberDto>(model, result);
            return result;
        }

        CurriculumNumberModel ConvertToModel(CurriculumNumberDto model) {
            var result = new CurriculumNumberModel();
            AutoMapperWrapper.Instance.Map<CurriculumNumberDto, CurriculumNumberModel>(model, result);
            return result;
        }

        private JsonResult JsonResult(int code, string msg, bool isallowGet) {

            if (isallowGet)
                return Json(new { status = code, message = msg }, JsonRequestBehavior.AllowGet);

            return Json(new { status = code, message = msg });
        }
    }
}

RedCdn.ClassRoom.BMS/Views/CurriculumNumber/Edit.cshtml
@using Redcdn.ClassRoom.Facade;
@model RedCdn.ClassRoom.BMS.CurriculumNumberModel

@{
    ViewBag.Title = ViewBag.TitleDesc;
    var action = ViewBag.IsCreate ? "create" : "edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pageSize = PageData["PageSize"];
    var page = @ViewBag.Page;


    string valuedt = action == "create?" ? "" :Model.StarTime.GetDateTimeFormats('t')[0];
}

<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/layer/layer.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/my97/WdatePicker.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type=" text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css"></link>

<div class="clear">
    @using (Html.BeginForm(action, "CurriculumNumber", new { page = @page }, FormMethod.Post)) {
        <div class="clear">
            <h6 class="tips"><span>@ViewBag.TitleDesc</span></h6>
            <ul class="management" ngdesc="@ViewBag.TitleDesc">
                <li>
                    <span><font>课序：</font></span>
                    @Html.HiddenFor(model => model.Id)
                    @Html.TextBoxFor(model => model.Name, new { @id = "ccnumber", @name = "ccnumber" })
                    <font class="wenzig">@Html.ValidationMessageFor(model => model.Name)</font>
                </li>
                <li><span><font> 课序上课时间：</font></span><input id="StarTime" name="StarTime" onfocus="WdatePicker({skin:'whyGreen',dateFmt:'HH:mm:ss'})" type="text" value="@valuedt" class="Wdate"></li>
                <li><span><font> 课序上课时长(分钟)：</font></span>@Html.TextBoxFor(model => model.Duration, new { @id = "duration", @name = "duration", @maxlength = 3, @onkeyup = @"value=value.replace(/[^(\d)]/g,'')", @onafterpaste = @"this.value=this.value.replace(/\D/g,'')", @style = "ime-mode:inactive" })<font class="wenzig">@Html.ValidationMessageFor(model => model.Duration)</font></li>
                <li style="height: 120px; margin-top: 60px;">
                    <input id="edit-submit" style="margin-top: 0; margin-left: 131px;" type="button" class="submit" onmouseover=" this.style.backgroundPosition = 'left -33px' " onmouseout=" this.style.backgroundPosition = 'left top' " value="保 存" />
                    <a href="@Url.Action("index", "CurriculumNumber", new { page = @ViewBag.Page, count = @pageSize })#menu=ChildMenu3">
                        <input style="margin-top: 0; margin-left: 60px;" type="button" class="submit" onmouseover=" this.style.backgroundPosition = 'left -33px' " onmouseout=" this.style.backgroundPosition = 'left top' " value="返 回" />
                    </a>
                    <br />
                </li>
            </ul>
        </div>
    }
</div>

<script type="text/javascript">
    $(function() {
        createnavigation();
       // loadData();
        $('input#edit-submit').bind('click', function(e) {
            e.preventDefault();

            if (!validate())
                return false;

            submitForm('form');
        });
    });

    function loadData() {
        laydate({
            elem: '#StarTime',
            format: 'HH:mm:ss', // 分隔符可以任意定义，该例子表示只显示年月
            festival: true, //显示节日
            choose: function (datas) { //选择日期完毕的回调
               // debug alert('得到：' + datas);
            }
        });
    }

    function submitForm(formid) {

        $(formid).ajaxSubmit({
            success: function(result, statusText) {

                if (result.success == false) {
                    layer.msg(result.message);
                } else {
                    var href = '@Url.Action("index", "CurriculumNumber")';
                    href += '?page=' + '@ViewBag.Page';
                    href += '&' + 'count=' + '@pageSize' + '#menu=ChildMenu3';
                    location.href = href;
                }
            },
            error: function (result) {
                layer.msg(result.message);
            },
            complete: function (result) {
                if (result.success == false)
                    layer.msg(result.message);
            }
        });
    }

    function validate(e) {

        var gradename = $('#ccnumber').val();
        var duration = $('#duration').val();
        var starttime = $('input#StarTime').val();

        if (gradename == "" || gradename == null) {
            layer.msg('请输入课序');
            return false;
        }
        if (duration == "" || duration == null) {
            layer.msg('请输入课序时长');
            return false;
        }

        if (duration <= 0) {
            layer.msg('课序时长必须大于0');
            return false;
        }

        if (starttime == "" || starttime == null) {
            layer.msg('请选择课序上课开始时间');
            return false;
        }

        return true;
    }

    /*创建面包屑导航菜单*/
    function createnavigation() {
        var ngDesc = $('ul.management').attr('ngdesc');

        var div = $('div.position');
        div.html('');
        div.append('当前位置： <a href="/">首页 </a> >' + ngDesc);
    }
</script>

RedCdn.ClassRoom.BMS/Views/CurriculumNumber/Index.cshtml
@using RedCdn.ClassRoom.BMS;
@using Redcdn.ClassRoom.Facade;
@model RedCdn.ClassRoom.BMS.Models.IndexPaging<CurriculumNumberModel>

@{
    ViewBag.Title = "课序列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pageSize = PageData["PageSize"];
}

<link href="@Url.Content("~/Content/css/jquery-paging.css")" rel="stylesheet" type="text/css"></link>
<script src="@Url.Content("~/Scripts/layer/layer.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/content-list-method.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-paging.js")" type="text/javascript"></script>

<ul class="clear view">
    <a href="@Url.Action("Edit", "CurriculumNumber")#menu=ChildMenu3" class="bigbtn">添加课序</a>
</ul>
<div id="ccnumber-render">
    @{Html.RenderPartial("_CurriculumNumberList", Model.Paging);}
</div>

<!--进行分页的div必须按照包含下述attr-->
<div id="query-paging" total-count="@Model.Paging.TotalCount" page-size="@pageSize" div-render="ccnumber-render" paging-url="@Url.Action("query", "CurriculumNumber")" class="page clear">
</div>

<script type="text/javascript">
    $(function () {
        createnavigation();

        /*注册分页需要的url信息，生成分页链接，后期点击分页使用*/
        paging("query-paging"/*显示分组链接的divid*/,
            "grouplist"/*渲染分组的tableid*/);
    });

    function ajaxsuccess(data) {
        /*首先填充查询结果，以便获取totalcount*/
        $('div#ccnumber-render').html(data);

        /*将table上的totalcount赋值到divpaging，用于设置分页链接是否显示*/
        var count = $('#grouplist').attr('total-count');

        /*如果没有数据，提示用户*/
        if (count == 0)
            layer.msg("没有满足条件的数据", { time: 1000 });

        /*设置分页总数*/
        var divpaging = $('div#query-paging');
        console.log('totalcount:' + count);
        divpaging.attr('total-count', count);

        /*注册分页需要的url信息，生成分页链接，后期点击分页使用*/
        paging("query-paging"/*显示分组链接的divid*/,
            "grouplist"/*渲染分组的tableid*/);
    }


    /*创建面包屑导航菜单*/
    function createnavigation() {
        var div = $('div.position');
        div.html('');
        div.append('当前位置: <a href="/">首页</a> > 课序列表');
    }
</script>

RedCdn.ClassRoom.BMS/Views/CurriculumNumber/_CurriculumNumberList.cshtml
@using Redcdn.ClassRoom.Facade;
@using RedCdn.ClassRoom.BMS;
@model PagingQueryResultDto<CurriculumNumberModel>
    
@{
    var page = 0;
    int.TryParse(Request.QueryString["page"], out page);
}

<table total-count="@Model.TotalCount" page-size="@ViewBag.PSize" current-page="@page" border="0" cellpadding="0" cellspacing="0" class="grouplist view" id="grouplist" style="margin-right:34px;">
    <thead>
        <tr>
            <td width="59">课序</td>
            <td width="59">上课时间</td>
            <td width="59">课节时长(分钟)</td>
            <td width="137">操作</td>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in @Model.Result) {
            <tr>
                <td>@item.Name </td>
                <td>@item.StarTime.GetDateTimeFormats('t')[0] </td>
                <td>@item.Duration </td>
                <td><a id="a=edit" href="@Url.Action("edit", "CurriculumNumber", new { page = @page, id = @item.Id })#menu=ChildMenu3">编辑</a>&nbsp;&nbsp;<a url="@Url.Action("delete", "CurriculumNumber", new { id = @item.Id })" delete-hint="选中课序" id="a-delete" href="###">删除</a></td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(function () {
        deletecontentfromlist('/CurriculumNumber/index');
    });

</script>