RedCdn.ClassRoom.BMS/Controllers/H5Controller.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Redcdn.ClassRoom.Facade;

namespace RedCdn.ClassRoom.BMS.Controllers {
    public class H5Controller : ControllerBase {

        public ActionResult LivePlay(int id) {
            string iosplay_templet = "{$ios_playurl$}";
            string pcplay_templet = "{$pc_playurl$}";

            try {
                string html = ReadH5Templet();

                var dto = FacadeFactory.Instance.Get<ILiveClassRoomManager>().Get(id);
                var viewModel = Mapper.Map<LiveClassRoomDto, LiveClassroomModel>(dto);

                ViewBag.PlayUrl = viewModel.LiveStreamUrl;

                string viewhtml = html.Replace(iosplay_templet, viewModel.LiveStreamUrl + ".m3u8")
                    .Replace(pcplay_templet, viewModel.LiveStreamUrl+".flv");

                //string debugurl = "http://192.168.12.177:20017/hls.cms.com/i98878b6e79fd450da9c20c4c2df68528.m3u8";
                //string viewhtml = html.Replace(iosplay_templet, debugurl)
                //    .Replace(pcplay_templet, debugurl);

                return Content(viewhtml);
            } catch (Exception ex) {
                return View("~/Views/logo/index.cshtml");
            }
        }


        string ReadH5Templet() {
            StringBuilder sb = new StringBuilder();
            string filename = Server.MapPath("/Scripts/h5/templet.html");
            using (FileStream fs = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)) {
                using (StreamReader reader = new StreamReader(fs)) {
                    while (reader.Peek() > 0) {
                        sb.AppendLine(reader.ReadLine());
                    }
                }
            }

            return sb.ToString();
        }
    }
}

RedCdn.ClassRoom.BMS/Controllers/LiveClassRoomController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using RedCdn.ClassRoom.BMS.Models;
using Redcdn.ClassRoom.Facade;

namespace RedCdn.ClassRoom.BMS.Controllers
{
    [Authorize]

    public class LiveClassRoomController :ControllerBase
    {
        int pageSize = SettingConfig.Instance.PageSize;

        public ActionResult Index(int page = 0, int count = 0)
        {
            var pagep = CreateQueryPageParameter(page, pageSize);

            return GetIndexView("index",  pagep);
        }

        ActionResult GetIndexView(string viewname,ContentQueryPageParameter pagep)
        {
            var index = new IndexPaging<LiveClassroomModel>();
            index.CurriculumEidtInfo = CurriculumEidtInfo.Load();
            var queryList = FacadeFactory.Instance.Get<ILiveClassRoomManager>().GetList(pagep);
            QueryExtracted(index.Paging, queryList);
            index.Paging.TotalCount = queryList.TotalCount;

            return View(viewname, index);
        }

     
        public ActionResult Query(int page = 0, int count = 0) {
            var pagep = CreateQueryPageParameter(page, count);

            var paging = new PagingQueryResultDto<LiveClassroomModel>();
            var queryList = FacadeFactory.Instance.Get<ILiveClassRoomManager>().GetList(pagep);
            QueryExtracted(paging, queryList);
            paging.TotalCount = queryList.TotalCount;

            return PartialView("_LiveClassRoomList", paging);
        }

        public ActionResult Detail(int id, int page = 0)
        {
            try
            {
                ViewBag.Page = GetInt(page);
                ViewBag.TmpId = id;

                var dto = FacadeFactory.Instance.Get<ILiveClassRoomManager>().Get(id);
                var viewModel = Mapper.Map<LiveClassRoomDto, LiveClassroomModel>(dto);

               // ViewBag.PlayUrl = viewModel.LiveStreamUrl;
                string[] tmpplayurl= viewModel.LiveStreamUrl.Split(',');

                if (tmpplayurl.Length>1)
                    ViewData["playurl-pc"] = tmpplayurl[0];
                else
                    ViewData["playurl-pc"] = viewModel.LiveStreamUrl;

                return View("Detail", viewModel);
            }
            catch (Exception ex)
            {
                return View("Detail", new LiveClassroomModel());
            }
        }


      


        ContentQueryPageParameter CreateQueryPageParameter(int page, int count) {
            ViewBag.PSize = pageSize;
            return new ContentQueryPageParameter() { StartIndex = page, PageSize = count, OrderFields = new List<string> { "id" }, OrderFlag = true };
        }

        private void QueryExtracted(PagingQueryResultDto<LiveClassroomModel> paging, PagingQueryResultDto<LiveClassRoomDto> queryList) {
            queryList.Result.ForEach(r => {
                var viewModel = Mapper.Map<LiveClassRoomDto, LiveClassroomModel>(r);
                paging.Result.Add(viewModel);

            });
        }



        int GetInt(int num) {
            return num < 0 ? 0 : num;
        }
    }
}

    

RedCdn.ClassRoom.BMS/Views/LiveClassRoom/Detail.cshtml
@model RedCdn.ClassRoom.BMS.LiveClassroomModel
@{
    ViewBag.Title = "查看课堂直播";
    Layout = "~/Views/Shared/_Layout.cshtml";
     var pageSize = PageData["PageSize"];
      var page = @ViewBag.Page;
}

<script src="@Url.Content("~/Scripts/swfembed.js")" type="text/javascript"></script>

<div class="clear">
    <h6 class="tips"><span id="sptitle">查看课堂直播</span></h6>
    <div class="ziye-cont">
        <div class="info-l" style="position:relative">
            <div class="video">
                <div style=" z-index: 99999; position: absolute;  height: 290px;">
                    <div id="player"></div> 
                </div>
            </div>
        </div>
        <!--视频说明-->

        <div class="info-r">
            <ul>
                <li>日        期：  @Model.LiveStreamBeginTime.ToString("yyyy/MM/dd/ HH:mm:ss")</li>
                <li>课        程：  @Html.DisplayFor(m => m.CurriculumName)</li>
                <li>年        级：  @Html.DisplayFor(m => m.GradeName)</li>
                <li>主讲教室：  @Html.DisplayFor(m => m.ClassRoomName)</li>
                <li>已  上  课：@Html.DisplayFor(m => m.Duration)</li>
                <li>移动端播放:<a href="@Url.Action("LivePlay", "H5", new { id = ViewBag.TmpId })">http://@Request.Url.Host:@Request.Url.Port@Url.Action("LivePlay", "H5", new { id = ViewBag.TmpId })</a> </li>
                <li>
                    <a href="@Url.Action("index", "liveclassroom", new { page = page, count = pageSize })"><input style="margin-top:0; margin-left:12px;" type="button" class="submit" onmouseover="this.style.backgroundPosition='left -33px'" onmouseout="this.style.backgroundPosition='left top'" value="返 回"></a>
                </li>
                
            </ul>
        </div>
        <!--视频说明-->
    </div>
</div>
<script type="text/javascript">
    $(function () {
        createnavigation();
        initPlayer();
    });
    

    function initPlayer() {
        var option = {
            url: '@ViewData["playurl-pc"]',
            ctype: 1,
            isautoplay: 1,
            divid: 'player',
            width: 440,
            height: 290,
            buffermsec: 1000,
            playerdesc: '同步课堂v1.0'
        };
        playvideo(option);
    }

    function createnavigation() {

        var tille = $('#sptitle').text();
        var div = $('div.position');
        div.html('');
        div.append('当前位置： <a href="/">首页 </a> ><a href="@Url.Action("index","liveclassroom")">课堂监看 </a> >' + tille);
    }
</script>

RedCdn.ClassRoom.BMS/Views/LiveClassRoom/Index.cshtml
@using RedCdn.ClassRoom.BMS;
@using Redcdn.ClassRoom.Facade;
@model RedCdn.ClassRoom.BMS.Models.IndexPaging<LiveClassroomModel>

@{
    ViewBag.Title = "课堂监看";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var pageSize = PageData["PageSize"];
}

<link href="@Url.Content("~/Content/css/jquery-paging.css")" rel="stylesheet" type="text/css"></link>
<script src="@Url.Content("~/Scripts/layer/layer.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/content-list-method.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-paging.js")" type="text/javascript"></script>

<ul class="clear view">
    <li class="text"> 正在上课的同步教室列表 </li>
</ul>
<div id="liveclassroom-render">
    @{Html.RenderPartial("_LiveClassRoomList", Model.Paging);}
</div>

<!--进行分页的div必须按照包含下述attr-->
<div id="query-paging" total-count="@Model.Paging.TotalCount" page-size="@pageSize" div-render="liveclassroom-render" paging-url="@Url.Action("query","liveclassroom")" class="page clear"> 
</div>
<script type="text/javascript">
    $(function () {
        createnavigation();

        /*注册分页需要的url信息，生成分页链接，后期点击分页使用*/
        paging("query-paging"/*显示分组链接的divid*/,
            "grouplist"/*渲染分组的tableid*/);
    });

    function ajaxsuccess(data) {
        /*首先填充查询结果，以便获取totalcount*/
        $('div#liveclassroom-render').html(data);

        /*将table上的totalcount赋值到divpaging，用于设置分页链接是否显示*/
        var count = $('#grouplist').attr('total-count');

        /*如果没有数据，提示用户*/
        if (count == 0)
            layer.msg("没有满足条件的数据", { time: 1000 });

        /*设置分页总数*/
        var divpaging = $('div#query-paging');
        console.log('totalcount:' + count);
        divpaging.attr('total-count', count);

        /*注册分页需要的url信息，生成分页链接，后期点击分页使用*/
        paging("query-paging"/*显示分组链接的divid*/,
            "grouplist"/*渲染分组的tableid*/);
    }


    /*创建面包屑导航菜单*/
    function createnavigation() {
        var div = $('div.position');
        div.html('');
        div.append('当前位置: <a href="/">首页</a> > 课堂监看');
    }
</script>

RedCdn.ClassRoom.BMS/Views/LiveClassRoom/_LiveClassRoomList.cshtml
@using Redcdn.ClassRoom.Facade;
@using RedCdn.ClassRoom.BMS;
@model PagingQueryResultDto<LiveClassroomModel>
    
@{
    var page = 0;
    int.TryParse(Request.QueryString["page"], out page);
}

<table total-count="@Model.TotalCount" current-page="@page" border="0" cellpadding="0" cellspacing="0" class="grouplist view" id="grouplist" style="margin-right:34px;">
    <thead>
        <tr>
            <td width="78">主讲教室</td>
            <td width="59">年级</td>
            <td width="222" style="width:135px; white-space:normal; word-break:break-all;">课程名称</td>
            <td width="98">上课时间 </td>
            <td width="137">操作</td>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var item in @Model.Result) {
            <tr>
                <td>@item.ClassRoomName </td>
                <td>@item.GradeName</td>
                <td>@item.CurriculumName</td>
                <td>@item.LiveStreamBeginTime.GetDateTimeFormats('t')[0]</td>
                <td><a id="a=edit" href="@Url.Action("Detail", "liveclassroom", new { page = @page, id = @item.Id })">查看实时直播</a>&nbsp;&nbsp;</td>
            </tr>
        }
    </tbody>
</table>