RedCdn.ClassRoom.BMS/Controllers/LogoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GM.Utilities;

namespace RedCdn.ClassRoom.BMS.Controllers
{
    public class LogoController :ControllerBase
    {
        //
        // GET: /Logo/

        public ActionResult Index()
        {
            string filePath = GetLogo();
            ViewBag.ImagePath = filePath;
            return View();
        }

        public ActionResult GetSchoolLogo()
        {
            string filePath = GetLogo();
            if (System.IO.File.Exists(Server.MapPath("~/" + filePath)))
                return Json(new { state = 0, path = "/"+filePath }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { state = -1, path = "pclogo不存在" }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public ActionResult UploadLogo(HttpPostedFileBase file)
        {
            if (file == null) {
                return Json(new { success = false, message = "没有选择文件。" });
            }

            var ext = Path.GetExtension(file.FileName);
            var fileName = Path.Combine(Request.MapPath("~/UpFile"), "pclogo"+ext);
            try
            {
                DeleteFile();
                file.SaveAs(fileName);
                return Json(new { success = true, message = "修改成功。", filename = Path.GetFileName(fileName) });
            }
            catch (Exception ex)
            {
                Logger.WriteErrorFmt(Log.LogoManger, ex, "上传内容异常");
                return Json(new { success = false, message = ex.Message });
            }
        }

        void DeleteFile() 
        {
            new DirectoryInfo(Request.MapPath("~/UpFile")).GetFiles().ToList().ForEach(file => { System.IO.File.Delete(file.FullName); });
        }

        string GetLogo()
        {
            var list = new List<string>();
            GetSubFiles(new DirectoryInfo(Request.MapPath("~/UpFile")), list);
            if (list.Count > 0)
            {
                string logo = list[0].Substring(list[0].IndexOf("UpFile"), list[0].Length - list[0].IndexOf("UpFile"));
                return logo.Replace("\\","/");
            }
            
            return null;
        }

        private  void GetSubFiles(FileSystemInfo directory, List<string> fileList) {
            if (!directory.Exists) return;
            try {
                DirectoryInfo dir = directory as DirectoryInfo;
                //不是目录 
                if (dir == null) return;
                FileSystemInfo[] files = dir.GetFileSystemInfos();
                for (int i = 0; i < files.Length; i++) {
                    FileInfo file = files[i] as FileInfo;
                    if (file != null) {
                        fileList.Add(file.FullName);
                    } else {
                        GetSubFiles(files[i], fileList);
                    }
                }
            } catch (Exception ex) {
                throw ex;
            }
        }
    }
}

RedCdn.ClassRoom.BMS/Views/Logo/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var logopath = string.IsNullOrEmpty(ViewBag.ImagePath) ? Url.Content("~/Content/images/sc.png") : ViewBag.ImagePath;
}
<script src="@Url.Content("~/Scripts/layer/layer.js")" type="text/javascript"></script>

@using (Html.BeginForm("UploadLogo", "Logo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="clear">
    <h6 class="tips"><span>LOGO管理</span></h6>
   <div class="shangchuan"> 
	   <a href="#"><img id="img-logo" src="content/images/sc.png" width="260" height="70" border="0" /></a>
	   <p>
	   <div class="file-box">
  <form action="" method="post" enctype="multipart/form-data">
      <input type="file" accept="image/*" name="file" class="file" id="file" size="28" onChange="document.getElementById('textfield').value=this.value">
 <input type='text' name='textfield' id='textfield' class='txt'>  
 <input type='button' class='btn11' value='浏览...'>
 <input type="button" id ="upload" name="submit" class="btn11" value="上传">
  </form>
</div>
</p>
		<p>提示：支持jpg、jpeg、gif、png、bmp格式的图片</p>
		</div>
</div>
    <script>
        $(function () {
            var img = $('img');

            img.attr('src','@logopath');

            $('#upload').bind('click', function () {
                
                if (validate() != true) {
                    layer.msg("图片限于bmp,png,gif,jpeg,jpg格式");
                    return false;
                }

                $('form').ajaxSubmit({
                    success: function (result, statusText) {
                        console.log(result.success);
                        if (result.success == false) {
                            layer.msg(result.message);
                        } else {
                            var uploadfile = "/UpFile/" + result.filename;
                            img.attr('src', function() {
                                return uploadfile + "?" + Math.random();
                            });
                            layer.msg('上传成功', { time: 1000 });
                        }
                    },
                    error: function (result) {
                        layer.msg(result.message);
                    },
                    complete: function (result) {
                        if (result.success == false)
                            layer.msg(result.message);
                    }
                });
            });
        })

        function validate() {
            var filepath = $("input[name='file']").val();
            var extStart = filepath.lastIndexOf(".");
            var ext = filepath.substring(extStart, filepath.length).toUpperCase();
            if (ext != ".BMP" && ext != ".PNG" && ext != ".GIF" && ext != ".JPG" && ext != ".JPEG") {
                return false;
            }
            return true;
        }
       
    </script>
    
}